### ISSUE TITLE
Support Google Italy

### ISSUE THREAD

**Issue by fabrixx** [mozilla/speaktome#156]
Addon work for me only from here:
https://www.google.com/?gl=us&hl=en&pws=0&gws_rd=cr

My default Google Italy not work.

Another small issue:
I see only a blue filled icon not the MIC symbol on it.

**Comment by SoftVision-CarmenFat** [comment]
Hi @fabrixx and thanks for the report.

- The reason why Voice Fill doesn't work on Google Italy is because this domain is currently not supported and it only works in EN locales. 
- As for the icon issue, is this still reproducible on your side?
Can you please give us more details about your system, such as what Firefox version you have installed, operating system and other addons you may have installed?

**Comment by johngruen** [comment]
This is a dupe. We're going to open support for all all google tlds soon
