### ISSUE TITLE
Not working with  Google

### ISSUE THREAD

**Issue by abinabrahamanchery** [mozilla/speaktome#169]
I installed the addon on the latest firefox version, its working perfectly fine in the duckduckgo.com
but not exactly working in www.google.com 
![image](https://user-images.githubusercontent.com/5570791/29240692-0ffe0570-7f73-11e7-983d-651ba8313e15.png)

**Comment by abinabrahamanchery** [comment]
![image](https://user-images.githubusercontent.com/5570791/29240727-9aa9c146-7f73-11e7-9e78-81968b8ae8d4.png)
Its working perfectly on DuckDuckGo

**Comment by abinabrahamanchery** [comment]
![image](https://user-images.githubusercontent.com/5570791/29240732-af592730-7f73-11e7-8c84-6fa31626ca2b.png)
Working perfectly on DuckDuckGo

**Comment by SoftVision-CarmenFat** [comment]
Hi @abinabrahamanchery and thanks for the report.

As far as I can see from the screenshot attached, you are using **google.com.sa** which currently is not a Voice Fill supported domain.
In order to use Voice Fill on Google, please try one of the following suggestions:
1. Click on the "Use Google.com" link from the bottom right of the screen;
OR
2. Type www.google.com/ncr on the location bar and press Enter (this shouldn't allow you to be redirected to the Google SA domain).

Please let me know if any of these work for you.

**Comment by johngruen** [comment]
Closing this as a dupe
