### ISSUE TITLE
Tracking Bug for UX Assets

### ISSUE THREAD

**Issue by johngruen** [mozilla/speaktome#18]
@fangshih, please add a link for all icons from your visual spec. Icons should be either SVG or Retina (@2x) pngs.

**Comment by aminalhazwani** [comment]
@johngruen what if we point to http://design.firefox.com/icons/? (jfyi we are currently working on design tokens for icons, colors, typography, ... either as npm module, json file, or will see!)

**Comment by ChenMorpheus** [comment]
@aminalhazwani I agree if we can have all icons in one place. However, most new created icons for Test Pilot experiments might only survive until experiments graduate. Except our point is to store all icons which ever appear in Firefox browser, would it be better to put these icons on Github for implementation purpose and collect them into Design System as long as they officially join the Firefox release channel?

The question here brings to another question. From my understanding, experiments on Test Pilot can't count as "official" Firefox products since the purpose is to validate the assumptions, and that's why we were told to create more openly and focus more on the quality instead of sticking to the current UX guidelines. Now we've followed Photon as much as possible, such as icon style, typography, but I might need to know how flexible we can do and what role Test Pilot is playing in Design System for the future direction. @johngruen What do you think?

**Comment by fangshih** [comment]
@johngruen Here are the icons in SVG 
https://github.com/youwenliang/testpilot-assets/tree/master/Speak_To_Me/00_Assets
Thanks!

**Comment by aminalhazwani** [comment]
@ChenMorpheus very interesting points!, thanks for sharing! I suggested to grab the icons from the photon design system because I noticed that most of speaktome icons (with the exception of the mic) are already hosted on http://design.firefox.com/icons/ :) BTW would be nice to have the mic icon in our collection! These icons are hosted on github as well https://github.com/FirefoxUX/icons/tree/master/icons/new

That said I agree with you, Test Pilot could and should be more guidelines-free but if you use Photon assets it might be convenient for you to grab what is already hosted rather then having to upload it yourself once again.
