### ISSUE TITLE
Provide Animation State Information / Assets Voice Overlay

### ISSUE THREAD

**Issue by johngruen** [mozilla/speaktome#20]
@fangshih, we need to provide the team with an animation spec for speak to me. Let's touch base tomorrow to see how best to convert your ideas into code.

**Comment by fangshih** [comment]
For the animation assets part, I've uploaded some of them here. 
https://github.com/mozilla/testpilot-assets/tree/master/Speak_To_Me/00_Assets/Mic%20animation/SVG

1.Starting: [mic-start.svg](https://github.com/mozilla/testpilot-assets/blob/master/Speak_To_Me/00_Assets/Mic%20animation/SVG/mic-start.svg)
2.loading: [mic-spinning.svg ](https://github.com/mozilla/testpilot-assets/blob/master/Speak_To_Me/00_Assets/Mic%20animation/SVG/mic-spinning.svg)
_( for this one, because the svg can't really show the gradient, we maybe need to figure out how to show the spinning gradient here. should I just provide the spinning color? )_ 
3.Finish ( green) : [mic-done.svg](https://github.com/mozilla/testpilot-assets/blob/master/Speak_To_Me/00_Assets/Mic%20animation/SVG/mic-done.svg)  
4.Error ( Red ): [mic-error.svg](https://github.com/mozilla/testpilot-assets/blob/master/Speak_To_Me/00_Assets/Mic%20animation/SVG/mic-error.svg)

Here are the error example video. 
![error-video](https://user-images.githubusercontent.com/4862573/28358201-962bbf24-6ca0-11e7-8ade-e5f262ae01f2.gif)
