### ISSUE TITLE
Settings > File An Issue points to the wrong repository

### ISSUE THREAD

**Issue by urzds** [mozilla/speaktome#253]
The [Voice Fill experiment page](https://testpilot.firefox.com/experiments/voice-fill) has a settings menu in the upper right corner, which contains a "File An Issue" link, which points to [issues in Test Pilot](https://github.com/mozilla/testpilot/issues) instead of issues in this repository, which in turn might lead to reports in the wrong location (see e.g. mozilla/testpilot#3331).

**Comment by Softvision-CristinaBadescu** [comment]
Actually, this is the correct behavior since the "Settings" button belongs to the "Test Pilot" site, and "File an issue" actually refers to Test Pilot. This behavior is available when navigating to any of Test Pilot experiments pages, not only Voice Fill.

However, you'll find the corresponding experiments issue repository in the "Bug Reports" section, under the experiment name and icon, as you can see in the attached screenshot.
![experiment issue repository](https://user-images.githubusercontent.com/31244235/35974534-2a0118f2-0ce2-11e8-8a63-5ee230fa2bfa.png)

**Comment by urzds** [comment]
Thanks for the explanation.

> Actually, this is the correct behavior since the "Settings" button belongs to the "Test Pilot" site, and "File an issue" actually refers to Test Pilot. This behavior is available when navigating to any of Test Pilot experiments pages, not only Voice Fill.

This is IMO not clear for the user.
