### ISSUE TITLE
Implement the GA metrics

### ISSUE THREAD

**Issue by wresuolc** [mozilla/speaktome#35]
As defined at https://github.com/mozilla/speaktome/blob/master/docs/metrics.md

**Comment by wresuolc** [comment]
flagging @rjweiss for data collection review

**Comment by wresuolc** [comment]
Voice Fill: UA-35433268-80

**Comment by rjweiss** [comment]
Who owns delivering the analysis described in these docs?

**Comment by chuckharmston** [comment]
@rjweiss that will be @andrenatal.

Of note: [`testpilot-ga`](https://github.com/mozilla/testpilot-ga) will make this go much more smoothly.

**Comment by rjweiss** [comment]
r+ on this request.  We're testing a new way of providing data review, so I'll be adding that here:

**1) Is there documentation that describes the schema for the ultimate data set available publicly, complete and accurate?**
Yes

**2) Is there a control mechanism that allows the user to turn the data collection on and off?**
Yes

**3) What type of data do the requested instruments or measurements fall under?**
No assertion of data types has been provided by the requesters.  Looking at the documentation, these all appear to be collection type 2 

**4) Is the data collection default-on or default-off?**
I'm assuming default-on for all users in the Test Pilot trial.

**5) Does the instrumentation include the addition of any new identifiers (whether anonymous or otherwise; e.g., username, random IDs, etc.  See the appendix for more details)?**
No.  As with all Test Pilot trials, there is a UUID to allow for tracking events throughout the event measurement sequence and a Google Analytics property ID.  Neither of these are new to this proposal, however.

**6) Is the data collection covered by the existing Firefox privacy notice? If unsure: escalate to legal.**
Yes

**7) Does there need to be a check-in in the future to determine whether to renew the data?**
If the results of this Test Pilot study result in a decision to ship the feature to release, yes.  Otherwise, no.
