### ISSUE TITLE
Store the query results in a relational database

### ISSUE THREAD

**Issue by andrenatal** [mozilla/speaktome#6]

**Comment by relud** [comment]
to save audio files do this: accept a config from the environment for a bucket name, use the aws sdk to write to that bucket, don't provide credentials (in our environment credentials are handled automatically), and handle files being deleted (without notice) over time when reading from s3, so that we can configure automatic deleting of old files

**Comment by andrenatal** [comment]
Duplicate of: https://github.com/mozilla/speech-proxy/issues/14
